"""add language to posts

Revision ID: 364db068d4c0
Revises: ac8830b25700
Create Date: 2023-04-07 13:12:21.732014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364db068d4c0'
down_revision = 'ac8830b25700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
